//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Reservation_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin_Detail
    {
        public string Admin_userName { get; set; }
        public string Admin_pass { get; set; }
        public int Admin_id { get; set; }
    }
}
