//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Reservation_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancel_Ticket
    {
        public decimal Cancelation_Id { get; set; }
        public Nullable<decimal> Ticket_no { get; set; }
        public Nullable<decimal> Train_id { get; set; }
        public string Status { get; set; }
    
        public virtual Trains_Detail Trains_Detail { get; set; }
    }
}
