//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_Reservation_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fair_S
    {
        public int SequenceNO { get; set; }
        public Nullable<decimal> Train_id { get; set; }
        public Nullable<decimal> C1AC { get; set; }
        public Nullable<decimal> C2AC { get; set; }
        public Nullable<decimal> C3AC { get; set; }
    
        public virtual Trains_Detail Trains_Detail { get; set; }
    }
}
